spring:
  config:
    activate:
      on-profile: default
  application:
    name: api
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace